language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

before_deploy:
  - PREV_VERSION="$(git describe --tags --abbrev=0 --match='v[0-9]*' HEAD^)"
  - RELEASE_NOTES="$(git log --reverse --no-merges --format='* %s' "$PREV_VERSION"..HEAD)"

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  body: |-
    - One
    - Two
    - Three
    - Four
  on:
    branch: master
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
