language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  on:
    branch: master
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
